config/routes.rb
Rails.application.routes.draw do
  root 'blog#index'
  get 'blog/index'

  get 'blog/info'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
  end

  def info
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/blog/index.html.erb
<div class="outer">
    <div class="middle">
        <p>Introducing Gah-Young</p>
        <p></p>
        <div class="inner">
            <p>안녕하세요 :)<br>멋쟁이 사자처럼 6기<br>성균관대학교 서가영입니다!</p>
            <%= button_to "More", blog_info_path, :class => "button", :id => "info", :method => :get %>
            <%= button_to "Facebook", "https://www.facebook.com/sarahseoh?ref=bookmarks", :class => "button", :id => "fb", :method => :get %>
            <%= button_to "Instagram", "https://www.instagram.com/sarahseoh/?hl=ko", :class => "button", :id => "insta", :method => :get %>
        </div>
    </div>
</div>

app/views/blog/info.html.erb
<h1 class="more">More about Gah-Young</h1>
<a class="info" href="https://www.facebook.com/photo.php?fbid=1634168513308641&set=a.111139385611569.11239.100001465235837&type=3&theater">서가영</a>
<ul class="about">

    <li>1998.05.07 출생</li>
    <li>여자</li>
    <li>과천 통학중</li>
    <li>프로그래밍 잘하고 싶음</li>
    <li>어떻게 생겼는지 궁금하면 이름 클릭</li>
    
</ul>

<h2 class="info">성균관대학교 소속</h2>
<ul class="about">
    <li>경영학과 17학번</li>
    <li>배드민턴 동아리 라켓챌린지 부회장</li>
    <li>멋쟁이 사자처럼 6기</li>
</ul>

<h2 class="info">취미</h2>
<ul class="about">
    <li>배드민턴</li>
    <li>사진 찍기(잘 안보이겠지만 배경도 별사진 찍은거...☞☜) </li>
    <li>오버워치 하기/보기</li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Introduce</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- 합쳐지고 최소화된 최신 CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    
    <!-- 부가적인 테마 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
    
    <!-- 합쳐지고 최소화된 최신 자바스크립트 -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>